development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  database: dramatech_development
  username: deanpapastrat

test: &test
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  database: dramatech_test
  username: deanpapastrat

production:
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  min_messages: ERROR
  reconnect: false